### ISSUE TITLE
UNIT TESTS

### ISSUE THREAD

**Issue by marabesi** [marabesi/laration#10]
This package doesn't have any unit tests (or integration). I was wondering what is the best approach to start writing tests.

Any idea?

**Comment by carusogabriel** [comment]
We could make a list of what do we wanna test and start to code! Ex:
- [ ] Test get all configs;
- [ ] Test get specific configs;

**Comment by marabesi** [comment]
sounds good to me,

I just created a new branch named unit tests (https://github.com/marabesi/laration/tree/unit-tests)


Let's make it happen!!!!
